language: php
php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  global:
    - APP_KEY=32CharStringabcdefghijklmnopqrst

install: cd Application && composer install --dev
script:
  - vendor/phpunit/phpunit/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml
