language: php
php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

install: cd Application && composer install --dev
script:
  - vendor/phpunit/phpunit/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml
