sudo: required

services:
  - docker

# language: php

# php:
# 	- 5.6
# 	- 7.0
# 	- hhvm
# 	- nightly

before_install:
  - cd Application

install: 
  - curl icanhazip.com
  - cd deployment
  - docker build -t level_crossing_predictor .
  - docker run -d -v "`pwd`/data":/data -v "`pwd`/../":/src -p 7002:5432 -p 7001:3306 -p 7000:80 level_crossing_predictor
  - docker ps -a
before_script:
script:
  - docker exec level_crossing_predictor /bin/bash -c "cd /src; composer test:webapp"
  - docker exec level_crossing_predictor /bin/bash -c "cd /src; composer test:php"
